name: Fetch Data
permissions:
  contents: write
on:
  workflow_call: # Called by pipeline.yml
  workflow_dispatch: # Manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust_fetch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Prepare cargo cache dirs
        run: mkdir -p ~/.cargo/registry ~/.cargo/git

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('rust_fetch/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('rust_fetch/Cargo.lock') }}

      - name: Prepare data directories
        run: |
          mkdir -p ../data/raw ../data/processed
          touch ../data/raw/fear_and_greed_history_5min.jsonl

      - name: Build project
        run: cargo build --release

      - name: Run scheduled fetch
        run: cargo run --release --bin fetch_data

      - name: Ensure processed folder exists
        run: mkdir -p ../data/processed

      - name: Validate JSONL file
        run: cargo run --release --bin validate_jsonl -- ../data/raw/fear_and_greed_history_5min.jsonl

      - name: Convert JSONL → Parquet
        run: cargo run --release --bin convert_jsonl_parquet -- ../data/raw/fear_and_greed_history_5min.jsonl ../data/processed/fear_and_greed_history_5min.parquet

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ../data/raw/fear_and_greed_history_5min.jsonl ../data/processed/fear_and_greed_history_5min.parquet
          git commit -m "chore: update fetched data" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
