name: Fetch Data

on:
  workflow_call: {}
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: fetch-data
  cancel-in-progress: true

env:
  RAW_DATA_DIR: ../data/raw
  PROCESSED_DATA_DIR: ../data/processed
  FEAR_GREED_FILE: fear_and_greed_history_5min.jsonl
  PARQUET_FILE: fear_and_greed_history_5min.parquet

jobs:
  fetch:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust_fetch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo registry & git index
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust_fetch/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Prepare data dirs & seed raw file
        run: |
          mkdir -p "$RAW_DATA_DIR" "$PROCESSED_DATA_DIR"
          touch "$RAW_DATA_DIR/$FEAR_GREED_FILE"

      - name: Build (release)
        run: cargo build --release

      - name: Fetch data
        run: cargo run --release --bin fetch_data

      - name: Validate JSONL
        run: cargo run --release --bin validate_jsonl -- "$RAW_DATA_DIR/$FEAR_GREED_FILE"

      - name: Convert JSONL → Parquet
        run: cargo run --release --bin convert_jsonl_parquet -- \
          "$RAW_DATA_DIR/$FEAR_GREED_FILE" \
          "$PROCESSED_DATA_DIR/$PARQUET_FILE"

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$RAW_DATA_DIR/$FEAR_GREED_FILE" "$PROCESSED_DATA_DIR/$PARQUET_FILE"
          git commit -m "chore(fetch): update fear and greed data" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
