name: Scheduled Data Fetch

on:
  schedule:
    - cron: "20 16 * * *" # At 16:10 UTC daily (19:20 Finland time)
  workflow_dispatch: # Manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust_fetch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('rust_fetch/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('rust_fetch/Cargo.lock') }}

      - name: Build project
        run: cargo build --release

      - name: Run scheduled fetch
        run: cargo run --release --verbose

      - name: Ensure processed folder exists
        run: mkdir -p ../data/processed

      - name: Convert JSONL → Parquet
        run: cargo run --release --bin convert_jsonl_parquet -- \
          ../data/raw/fear_and_greed_history_5min.jsonl \
          ../data/processed/fear_and_greed_history_5min.parquet
