name: Train Model

permissions:
  contents: write
on:
  workflow_call: # Called by pipeline.yml
  workflow_dispatch: # Manual trigger

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: python_train/environment.yml
          activate-environment: btc_predictor
          auto-activate-base: false

      - name: Train model
        shell: bash -l {0}
        run: |
          jupyter nbconvert --to notebook --execute python_train/linear_regression_training.ipynb --output linear_regression_training.ipynb --output-dir python_train

      - name: Commit model weights and notebook
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add models/*.csv models/*.json python_train/linear_regression_training.ipynb
          git commit -m 'Update model weights and notebook [skip ci]' || echo "No changes to commit"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
