name: Train and Commit Model

on:
  workflow_dispatch:
  push:
    paths:
      - 'python_train/src/train.py'
      - 'python_train/environment.yml'
      - 'python_train/data/**'
      - 'python_train/analysis.ipynb'
      - '.github/workflows/train_model.yml'

jobs:
  train-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: python_train/environment.yml
          activate-environment: btc_predictor
          auto-activate-base: false

      - name: Train model
        shell: bash -l {0}
        run: |
          python python_train/src/train.py

      - name: Commit model weights
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add models/*.csv
          git commit -m 'Update model weights [skip ci]' || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
